# Compose schema version
# version: '3.4'

# Overriding requirements

x-env:
  &defaults
  GET_HOSTS_FROM: dns
  FEDN_PACKAGE_EXTRACT_DIR: package
  FEDN_NUM_DATA_SPLITS: 5 # Number of data splits/clients

services:

  client1:
    image: fedn-client:0.9.2
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      # CLIENT_ID: 1
      FEDN_DATA_PATH: /app/package/data/clients/1/IOT_normal_base.pt
      # FEDN_MODEL_PATH: /app/package/client/model/1/local_model.pt # Possible way to use different client models if clients have different feature sizes
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - $PWD/data/:/app/package/data

  client2:
    image: fedn-client:0.9.2
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/data/clients/2/IOT_normal_base.pt
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - $PWD/data/:/app/package/data

  client3:
    image: fedn-client:0.9.2
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/data/clients/3/IOT_normal_base.pt
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - $PWD/data/:/app/package/data

  client4:
    image: fedn-client:0.9.2
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/data/clients/4/IOT_normal_base.pt
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - $PWD/data/:/app/package/data

  client5:
    image: fedn-client:0.9.2
    extends:
      file: ${HOST_REPO_DIR:-.}/docker-compose.yaml
      service: client
    environment:
      <<: *defaults
      FEDN_DATA_PATH: /app/package/data/clients/5/IOT_normal_base.pt
    deploy:
      replicas: 1
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - $PWD/data/:/app/package/data